<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PsyReaSFX.Desktop</AssemblyName>
    <RootNamespace>PsyReaSFX.Desktop</RootNamespace>
    <AssemblyVersion>0.7.23.9</AssemblyVersion>
    <FileVersion>0.7.23.9</FileVersion>
    <Version>0.7.23-desktop-alpha.4-light-rc.1</Version>
    <Authors>Psysia</Authors>
    <Product>PsyReaSFX Desktop</Product>
    <Description>Standalone sound asset browser and REAPER delivery companion.</Description>
    <ApplicationIcon>Assets\psyreasfx.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PsyReaSFX.Data\PsyReaSFX.Data.csproj" />
    <Resource Include="Assets\psyreasfx-icon.png" />
    <Resource Include="Assets\psyreasfx-hero.png" />
    <Resource Include="Assets\Fonts\Orbitron-VariableFont_wght.ttf" />
  </ItemGroup>
</Project>
